name: humanscoring
description: A new Flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 8.0.2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.0
  http: ^0.13.4
  dio: ^4.0.6


  firebase_core_platform_interface: ^4.5.1
  firebase_messaging: ^14.2.2
  image_picker: ^0.8.4+4
  sizer: ^2.0.15
  get: 4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0
  octo_image: ^1.0.2
  carousel_slider: ^4.1.1
  readmore: ^2.2.0
  percent_indicator: ^4.0.1
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  country_codes: ^2.2.0
  country_picker: ^2.0.19
  permission_handler: ^10.0.0
  qr_flutter: ^4.0.0
  share_plus: ^4.0.9
  path_provider: ^2.0.11
  file_picker: ^4.6.1
  # payment
  stripe_sdk: ^5.0.0-nullsafety.1
  # firebase packAge
  cloud_firestore: ^4.0.0
  flutter_local_notifications: ^9.4.0
  firebase_dynamic_links: ^5.0.12
  firebase_crashlytics: ^3.0.16
  package_info_plus: ^1.4.2
  open_store: ^0.2.4
  cached_network_image: ^3.2.0
  d_chart: ^0.0.4
  image_cropper: ^1.5.0
  intl_phone_field: ^3.1.0
  lottie: ^1.3.0
  video_player: ^2.4.5
  shimmer: ^2.0.0
  webview_flutter: ^2.1.0
  flutter_html: ^3.0.0-alpha.5
#  in_app_purchase: ^3.0.7
  open_file_safe: ^3.2.3
  url_launcher: ^6.1.6

  record: ^4.4.3
  audioplayers: ^1.0.1
  animations: ^2.0.7
  flutter_switch: ^0.3.2
  contacts_service: ^0.6.3

  firebase_analytics: ^10.1.1
  firebase_database: ^10.0.11
  firebase_storage: ^11.0.11
  flutter_zoom_drawer: ^3.0.3
  firebase_auth: ^4.1.3
  firebase_core:
  flutterfire_ui: ^0.4.3+20
  flutter_rating_bar: ^4.0.1
  five_pointed_star: ^1.0.3


  screenshot: ^1.3.0
  image_gallery_saver: ^1.7.1

  charts_flutter: ^0.12.0
  simple_polls: ^1.0.8

  shared_preferences: any
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/icon/bottomIcons/
    - assets/image/
    - assets/json/
    - assets/suggest/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 600
        - asset: assets/font/Roboto-Bold.ttf
          weight: 800

